# Generated by Django 5.0.3 on 2024-03-29 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myweb", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("oid", models.CharField(max_length=64, verbose_name="订单号")),
                ("name", models.CharField(max_length=32, verbose_name="商品名称")),
                ("price", models.CharField(max_length=32, verbose_name="价格")),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "未支付"), (1, "已支付")],
                        max_length=32,
                        verbose_name="支付状态",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        max_length=20,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myweb.userinfo",
                        verbose_name="客户姓名",
                    ),
                ),
            ],
        ),
    ]
